apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data: 
  {{ if .Values.airflow.web.password }}
  airflowweb-password:  {{ .Values.airflow.web.password | b64enc | quote }}
  {{ else }}
  airflowweb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  #{{- if .Values.postgresql.postgresPassword }}
  #postgresPassword: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  #{{- else }}
  #postgresPassword: {{ randAlphaNum 10 | b64enc | quote }}
  #{{- end }}
  #postgresUser: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  #{{- if .Values.redis.password }}
  #redisPassword: {{ .Values.redis.password | b64enc | quote }}
  #{{- else }}
  #redisPassword: {{ randAlphaNum 10 | b64enc | quote }}
  #{{- end }}